Repository pygame/pygame, pull requests merged in 2019-04, with the labels that each got.

#933 Drop event docs
  docs/reST/ref/event.rst
Labels: 2.1

#981 Fix deadlock in music module
  src_c/music.c
Labels: 1.9.6

#994 SDL2: Add unittest decorator to failing test
  test/display_test.py
Labels: SDL2

#963 Add attributes to pygame.version.vernum
  buildconfig/version.py.in
  docs/reST/ref/pygame.rst
  setup.py
Labels: 1.9.6

#984 Build smpeg from source in the manylinux build.
  buildconfig/manylinux-build/docker_base/Dockerfile-i686
  buildconfig/manylinux-build/docker_base/Dockerfile-x86_64
  buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl-libs.sh
  buildconfig/manylinux-build/docker_base/sdl_libs/smpeg.sha512
  test/mixer_music_test.py
Labels: 1.9.6
