Repository pygame/pygame, pull requests merged in 2020-09, with the labels that each got.

#1994 Changed drawing of ellipse
  src_c/draw.c
  test/draw_test.py
Labels: needs-review

#2065 use rwops for font loading
  src_c/font.c
  test/font_test.py
Labels: Android

#1584 post keydown events, closes #1580
  docs/reST/ref/event.rst
  src_c/event.c
  test/event_test.py
Labels: Android

#1946 Pylint pass for midi module
  src_py/midi.py
Labels: needs-review

#2077 Closes #1794. Added unittest for Surface.blit() for sizing and color.
  test/surface_test.py
Labels: Surface

#2096 supress import * lint warnings
  src_py/__init__.py
  src_py/_sdl2/__init__.py
  src_py/locals.py
Labels: Linters
