Repository pygame/pygame, pull requests merged in 2020-06, with the labels that each got.

#1887 Add two extra buttons from 5 button mouse to mouse.get_pressed()
  buildconfig/pygame-stubs/mouse.pyi
  docs/reST/ref/mouse.rst
  src_c/doc/mouse_doc.h
  src_c/mouse.c
  test/mouse_test.py
Labels: needs-review

#1913 Some colorkey test fixes
  test/surface_test.py
Labels: needs-review

#1919 Remove hard coded RGB bitshifts that don't work with SDL_MapRGB()/SDL_MapRGBA()
  examples/data/BGR.png
  examples/data/laplacian.png
  src_c/surface.c
  src_c/transform.c
  test/surface_test.py
  test/transform_test.py
Labels: needs-review

#1897 Keep all window events in SDL2
  src_c/event.c
Labels: event

#1921 Pylint fixes for locals.py
  src_c/constants.c
  src_py/locals.py
Labels: needs-review

#1925 A start on linting the sprite module
  examples/testsprite.py
  src_py/sprite.py
Labels: Code robustness, sprite

#1878 Refactor setup, add -stripped build option
  setup.py
Labels: Android, buildconfig

#1956 Avoid PEP393 deprecated APIs.
  src_c/base.c
  src_c/math.c
  src_c/pixelcopy.c
  src_c/surface.c
Labels: Python 3.11
