Repository pygame/pygame, pull requests merged in 2020-07, with the labels that each got.

#1988 Fix get_active() function so it works as described in docs on windows under SDL2.
  src_c/display.c
Labels: needs-review

#2013 Fix pylint formatting issues
  src_py/__init__.py
  src_py/_camera_opencv_highgui.py
  src_py/_camera_vidcapture.py
  src_py/_dummybackend.py
  src_py/_numpysndarray.py
  src_py/camera.py
  src_py/compat.py
  src_py/cursors.py
  src_py/ftfont.py
  src_py/sndarray.py
  src_py/surfarray.py
  src_py/threads/__init__.py
Labels: Linters

#2015 Fix aatrigon/aapolygon drawing horizontal edges
  src_c/SDL_gfx/SDL_gfxPrimitives.c
  test/gfxdraw_test.py
Labels: gfxdraw
