Repository pygame/pygame, pull requests merged in 2021-12, with the labels that each got.

#2882 Fix some typehints, clean stubs
  buildconfig/pygame-stubs/__init__.pyi
  buildconfig/pygame-stubs/_common.pyi
  buildconfig/pygame-stubs/_sdl2/controller.pyi
  buildconfig/pygame-stubs/_sdl2/video.pyi
  buildconfig/pygame-stubs/bufferproxy.pyi
  buildconfig/pygame-stubs/camera.pyi
  buildconfig/pygame-stubs/color.pyi
  buildconfig/pygame-stubs/constants.pyi
  buildconfig/pygame-stubs/cursors.pyi
  buildconfig/pygame-stubs/display.pyi
  buildconfig/pygame-stubs/draw.pyi
  buildconfig/pygame-stubs/event.pyi
  buildconfig/pygame-stubs/fastevent.pyi
  buildconfig/pygame-stubs/font.pyi
  buildconfig/pygame-stubs/freetype.pyi
  buildconfig/pygame-stubs/gfxdraw.pyi
  buildconfig/pygame-stubs/image.pyi
  buildconfig/pygame-stubs/key.pyi
  buildconfig/pygame-stubs/mask.pyi
  buildconfig/pygame-stubs/math.pyi
  buildconfig/pygame-stubs/midi.pyi
  buildconfig/pygame-stubs/mixer.pyi
  buildconfig/pygame-stubs/mouse.pyi
  buildconfig/pygame-stubs/music.pyi
  buildconfig/pygame-stubs/pixelarray.pyi
  buildconfig/pygame-stubs/pixelcopy.pyi
  buildconfig/pygame-stubs/rect.pyi
  buildconfig/pygame-stubs/sndarray.pyi
  buildconfig/pygame-stubs/sprite.pyi
  buildconfig/pygame-stubs/surface.pyi
  buildconfig/pygame-stubs/surfarray.pyi
  buildconfig/pygame-stubs/time.pyi
  buildconfig/pygame-stubs/transform.pyi
  docs/reST/ref/display.rst
Labels: Awaiting Merge

#2790 Continue on Sdl compose custom blend mode
  src_c/_sdl2/video.c
  src_c/cython/pygame/_sdl2/video.pxd
  src_c/cython/pygame/_sdl2/video.pyx
Labels: Awaiting Merge

#2826 Add docs to the CI-generated wheels
  .github/workflows/build.yml
  .github/workflows/ubuntu-sdist.yml
  buildconfig/appveyor.yml
  buildconfig/manylinux-build/build-wheels.sh
  docs/__init__.py
  docs/__main__.py
  docs/util.py
  setup.py
  test/docs_test.py
Labels: Awaiting Merge

#2859 Fix weird MacOS display surf weirdness
  src_c/display.c
Labels: Low Hanging Fruit, Awaiting Merge

#2894 Added .copy() to Vector2 and Vector3
  buildconfig/pygame-stubs/math.pyi
  docs/reST/ref/math.rst
  src_c/doc/math_doc.h
  src_c/math.c
  test/math_test.py
Labels: Awaiting Merge

#2880 Fix drawing of big ellipses
  src_c/draw.c
  test/draw_test.py
Labels: Low Hanging Fruit, Awaiting Merge

#2863 Renamed some Vector methods to keep consistency
  buildconfig/pygame-stubs/math.pyi
  docs/reST/ref/math.rst
  src_c/doc/math_doc.h
  src_c/math.c
  test/math_test.py
Labels: Low Hanging Fruit, Awaiting Merge

#2896 Changed AbstractGroup.draw() to return List[Rect]
  buildconfig/pygame-stubs/sprite.pyi
  docs/reST/ref/sprite.rst
  src_py/sprite.py
Labels: Low Hanging Fruit, Awaiting Merge

#2858 Improve MacOS icon
  setup.py
  src_c/display.c
  src_c/sdlmain_osx.m
  src_py/__pyinstaller/hook-pygame.py
  src_py/macosx.py
  src_py/pygame_icon.icns
  src_py/pygame_icon.svg
  src_py/pygame_icon.tiff
  src_py/pygame_icon_mac.bmp
Labels: Awaiting Merge

#2840 fix filenotfound errors on pathlib loading
  src_c/rwobject.c
Labels: Awaiting Merge

#2870 Fix misnamed class aliasing in init file
  src_py/__init__.py
Labels: Low Hanging Fruit, Awaiting Merge

#2854 C cleanups to remove more old compat code
  docs/reST/c_api/rect.rst
  docs/reST/ref/event.rst
  src_c/_camera.c
  src_c/_freetype.c
  src_c/_pygame.h
  src_c/_sdl2/touch.c
  src_c/_sprite.c
  src_c/alphablit.c
  src_c/base.c
  src_c/bufferproxy.c
  src_c/camera_v4l2.c
  src_c/camera_windows.c
  src_c/cdrom.c
  src_c/color.c
  src_c/constants.c
  src_c/cython/pygame/_sprite.pyx
  src_c/display.c
  src_c/draw.c
  src_c/event.c
  src_c/font.c
  src_c/freetype/ft_render.c
  src_c/freetype/ft_unicode.c
  src_c/freetype/ft_wrap.h
  src_c/gfxdraw.c
  src_c/image.c
  src_c/imageext.c
  src_c/include/_pygame.h
  src_c/include/pgcompat.h
  src_c/include/pgimport.h
  src_c/joystick.c
  src_c/key.c
  src_c/mask.c
  src_c/math.c
  src_c/mixer.c
  src_c/mouse.c
  src_c/music.c
  src_c/newbuffer.c
  src_c/overlay.c
  src_c/pgcompat.c
  src_c/pgcompat.h
  src_c/pgimport.h
  src_c/pixelarray.c
  src_c/pixelarray_methods.c
  src_c/pixelcopy.c
  src_c/rect.c
  src_c/rwobject.c
  src_c/scrap.c
  src_c/scrap_win.c
  src_c/scrap_x11.c
  src_c/sdlmain_osx.m
  src_c/surface.c
  src_c/surface.h
  src_c/surflock.c
  src_c/time.c
  src_c/transform.c
Labels: Awaiting Merge

#2920 Cython code modernizations
  src_c/cython/pygame/_sdl2/audio.pxd
  src_c/cython/pygame/_sdl2/audio.pyx
  src_c/cython/pygame/_sdl2/controller.pxd
  src_c/cython/pygame/_sdl2/mixer.pxd
  src_c/cython/pygame/_sdl2/sdl2.pxd
  src_c/cython/pygame/_sdl2/video.pxd
Labels: Awaiting Merge

#2923 Fix some "it's" -> "its" in the docs
  docs/reST/ref/camera.rst
  docs/reST/ref/draw.rst
  docs/reST/ref/event.rst
  docs/reST/tut/DisplayModes.rst
  docs/reST/tut/MoveIt.rst
  docs/reST/tut/SpriteIntro.rst
  docs/reST/tut/newbieguide.rst
  examples/aliens.py
  examples/pixelarray.py
Labels: docs

#2921 Renamed pygame.sprite.LayeredDirty.set_timing_treshold to pygame.sprite.LayeredDirty.set_timing_threshold
  buildconfig/pygame-stubs/sprite.pyi
  docs/reST/ref/sprite.rst
  src_c/doc/sprite_doc.h
  src_py/sprite.py
Labels: Awaiting Merge

#2930 Recorrected typehint for AbstractGroup
  buildconfig/pygame-stubs/sprite.pyi
  src_py/sprite.py
Labels: Low Hanging Fruit, Awaiting Merge

#2927 Fix rect drawing with width
  src_c/draw.c
  test/draw_test.py
Labels: Awaiting Merge

#2922 Freetype FileNotFound
  src_c/_freetype.c
  src_c/freetype.h
  src_c/freetype/ft_render.c
  src_c/freetype/ft_render_cb.c
  src_c/freetype/ft_wrap.c
  src_c/freetype/ft_wrap.h
  test/font_test.py
  test/freetype_test.py
Labels: Awaiting Merge

#2901 Reform colors across the examples
  examples/aacircle.py
  examples/aliens.py
  examples/camera.py
  examples/freetype_misc.py
  examples/joystick.py
  examples/midi.py
  examples/prevent_display_stretching.py
  examples/scroll.py
Labels: Awaiting Merge

#2904 fix GIL release in transform module
  src_c/transform.c
Labels: bug, transform, needs-review, threads

#2906 Working gamma test on windows
  test/display_test.py
Labels: bug, display, Compatability (Pygame 2)

#2944 freetype: Fix intermittent crash with test_font_file_not_found
  src_c/freetype/ft_wrap.c
Labels: bug, ftfont
