Repository pygame/pygame, pull requests merged in 2021-05, with the labels that each got.

#2580 Compatibility fix for GraalPython
  src_c/_pygame.h
Labels: buildconfig, pypy

#2576 (Freetype .render_to) Don't use -1 as error state.
  src_c/_freetype.c
Labels: Compatability (Pygame 2)

#2428 re-init bug fixes
  docs/reST/c_api/base.rst
  docs/reST/c_api/mixer.rst
  docs/reST/ref/display.rst
  src_c/_freetype.c
  src_c/_pygame.h
  src_c/base.c
  src_c/cdrom.c
  src_c/display.c
  src_c/event.c
  src_c/font.c
  src_c/include/_pygame.h
  src_c/include/pygame_mixer.h
  src_c/joystick.c
  src_c/mixer.c
  src_c/mixer.h
  src_c/time.c
  test/base_test.py
  test/display_test.py
Labels: base, display, event, help wanted, needs-review, needs-testing
