Repository pygame/pygame, pull requests merged in 2022-03, with the labels that each got.

#3043 Fix APPMOUSEFOCUS naming, update const values
  buildconfig/stubs/pygame/__init__.pyi
  buildconfig/stubs/pygame/constants.pyi
  docs/reST/ref/event.rst
  src_c/_pygame.h
  src_c/constants.c
  src_c/event.c
  src_py/locals.py
Labels: bug, event, Compatability (Pygame 2)

#3082 Pkgdata import in init for PyInstaller
  src_py/__init__.py
Labels: Awaiting Merge

#3041 Get rid of sprintf calls in the codebase
  src_c/_camera.c
  src_c/_freetype.c
  src_c/camera_v4l2.c
  src_c/color.c
  src_c/display.c
  src_c/event.c
  src_c/freetype/ft_render.c
  src_c/freetype/ft_wrap.c
  src_c/rect.c
  src_c/time.c
  src_py/__init__.py
  src_py/sysfont.py
Labels: C code, Code robustness

#3080 fix/norm function pointer calls for METH_NOARGS
  src_c/_camera.c
  src_c/_freetype.c
  src_c/_sdl2/touch.c
  src_c/base.c
  src_c/color.c
  src_c/display.c
  src_c/event.c
  src_c/font.c
  src_c/image.c
  src_c/imageext.c
  src_c/joystick.c
  src_c/key.c
  src_c/mask.c
  src_c/math.c
  src_c/mixer.c
  src_c/mouse.c
  src_c/music.c
  src_c/newbuffer.c
  src_c/rect.c
  src_c/scrap.c
  src_c/surface.c
  src_c/time.c
  src_c/transform.c
Labels: C code, misc portability, Awaiting Merge

#3074 Improve draw doc accuracy and example style
  docs/reST/ref/code_examples/draw_module_example.png
  docs/reST/ref/code_examples/draw_module_example.py
  docs/reST/ref/draw.rst
Labels: draw, docs
